# Generated by Django 5.0.1 on 2024-01-19 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('logo', models.ImageField(upload_to='Clients/')),
                ('slug', models.SlugField()),
                ('about_firm', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TechTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('overview', models.CharField(max_length=300)),
                ('thumbnail', models.ImageField(upload_to='Works/')),
                ('description', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
                ('usse_tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.techtool')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workcategory')),
            ],
        ),
    ]
